<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMx1leQW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMx1leQW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMx1leQW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMx1leQW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMx1leQW\App_KernelDevDebugContainer([
    'container.build_hash' => 'Mx1leQW',
    'container.build_id' => 'a74ce278',
    'container.build_time' => 1678895390,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMx1leQW');
