<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT6m0jYc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT6m0jYc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT6m0jYc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT6m0jYc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerT6m0jYc\App_KernelDevDebugContainer([
    'container.build_hash' => 'T6m0jYc',
    'container.build_id' => '7d2e408c',
    'container.build_time' => 1678891926,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT6m0jYc');
