<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1pxqiuJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1pxqiuJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1pxqiuJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1pxqiuJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1pxqiuJ\App_KernelDevDebugContainer([
    'container.build_hash' => '1pxqiuJ',
    'container.build_id' => 'e1525fbe',
    'container.build_time' => 1678895126,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1pxqiuJ');
